version: '3'
services:
  node-app:
    build: 
      context: .
      target: development
      # args:
      #   - NODE_ENV=dev
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=DEV
    command: npm run start-dev  #override cmd in docker file

        